checks:
  go: true
build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      environment:
        go:
          version: go1.9.2
      tests:
        override:
          - go-scrutinizer-run
          - govet-run
          - golint-run
#    tests:
#      project_setup:
#        override:
#          - 'true'
#      environment:
#        go:
#          version: go1.9.2
#      tests:
#        override:
#          - go-scrutinizer-run
#          - govet-run
#          - command: go test -v github.com/yakult1995/go-posgre-restapi
    coverage:
      tests:
        override:
          - command: go test -coverprofile=cover.out -v github.com/yakult1995/go-posgre-restapi
            coverage:
              file: 'cover.out'
              format: 'go-cc'
