checks:
  go: true
build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      environment:
        go:
          version: go1.9.2
      tests:
        override:
          - go-scrutinizer-run
          - govet-run
          - golint-run
    tests:
      project_setup:
        before:
          - "cd app"
        override:
          - 'true'
      environment:
        go:
          version: go1.9.2
      tests:
        override:
          - command: go test -v $(go list ./... | grep -v vendor)
    coverage:
      project_setup:
        before:
          - "cd app"
        override:
          - 'true'
      environment:
        go:
          version: go1.9.2
      tests:
        override:
          - govet-run
          - command: go test -coverprofile=cover.out -v $(go list ./... | grep -v vendor)
            coverage:
              file: 'cover.out'
              format: 'go-cc'
